<?php

########################################################################
# Extension Manager/Repository config file for ext: "meddevutils"
#
# Auto generated by Extension Builder 2013-04-18
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'medialis.net Developer Utilities',
	'description' => 'Collection of useful developer utilities',
	'category' => 'plugin',
	'author' => 'Tobias Schenk, Raphael Zschorsch',
	'author_email' => 'schenk@medialis.net, zschorsch@medialis.net',
	'author_company' => 'medialis.net UG (haftungsbeschränkt), medialis.net UG (haftungsbeschränkt)',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.0.3',
	'constraints' => array(
		'depends' => array(
			'extbase' => '1.3',
			'fluid' => '1.3',
			'typo3' => '4.5',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>